### ISSUE TITLE
Compile issues on windows with python3.8

### ISSUE THREAD

**Issue by unk1nd** [slinger360/NineRiFt-kivy#10]
Having some issues with compiling?

```
PS F:\git\NineRiFt-Lite\packaging> C:\Users\unk1nd\AppData\Local\Programs\Python\Python38\python.exe -m pip install -r requirements.txt
Collecting bleak
  Using cached bleak-0.7.1-py2.py3-none-any.whl (100 kB)
Collecting kivy
  Using cached Kivy-1.11.1.tar.gz (23.6 MB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\unk1nd\AppData\Local\Programs\Python\Python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\unk1nd\\AppData\\Local\\Temp\\pip-install-nypzdn4x\\kivy\\setup.py'"'"'; __file__='"'"'C:\\Users\\unk1nd\\AppData\\Local\\Temp\\pip-install-nypzdn4x\\kivy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\unk1nd\AppData\Local\Temp\pip-pip-egg-info-vdeayxoc'
         cwd: C:\Users\unk1nd\AppData\Local\Temp\pip-install-nypzdn4x\kivy\
    Complete output (83 lines):
    fatal: Not a git repository (or any of the parent directories): .git
    WARNING: Skipping page https://github.com/kivy-garden/garden/archive/master.zip because the HEAD request got Content-Type: application/zip.The only supported Content-Type is text/html
      ERROR: Command errored out with exit status 1:
       command: 'C:\Users\unk1nd\AppData\Local\Programs\Python\Python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\unk1nd\\AppData\\Local\\Temp\\pip-wheel-w9nlos_e\\cython\\setup.py'"'"'; __file__='"'"'C:\\Users\\unk1nd\\AppData\\Local\\Temp\\pip-wheel-w9nlos_e\\cython\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\unk1nd\AppData\Local\Temp\pip-wheel-ry4bu8s0'
           cwd: C:\Users\unk1nd\AppData\Local\Temp\pip-wheel-w9nlos_e\cython\
      Complete output (7 lines):
      Unable to find pgen, not compiling formal grammar.
      usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: setup.py --help [cmd1 cmd2 ...]
         or: setup.py --help-commands
         or: setup.py cmd --help

      error: invalid command 'bdist_wheel'
      ----------------------------------------
      ERROR: Failed building wheel for cython
    ERROR: Failed to build one or more wheels
     WARNING: The wheel package is not available.
     Traceback (most recent call last):
       File "C:\Users\unk1nd\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\installer.py", line 128, in fetch_build_egg
         subprocess.check_call(cmd)
       File "C:\Users\unk1nd\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 364, in check_call
         raise CalledProcessError(retcode, cmd)
     subprocess.CalledProcessError: Command '['C:\\Users\\unk1nd\\AppData\\Local\\Programs\\Python\\Python38\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\unk1nd\\AppData\\Local\\Temp\\tmpgvlmkexz', '--quiet', '--find-links', 'https://github.com/kivy-garden/garden/archive/master.zip', 'cython!=0.27,!=0.27.2,<=0.29.10,>=0.24']' returned non-zero exit status 1.

     During handling of the above exception, another exception occurred:

     Traceback (most recent call last):
       File "<string>", line 1, in <module>
       File "C:\Users\unk1nd\AppData\Local\Temp\pip-install-nypzdn4x\kivy\setup.py", line 1073, in <module>
         setup(
       File "C:\Users\unk1nd\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\__init__.py", line 143, in setup
         _install_setup_requires(attrs)
       File "C:\Users\unk1nd\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\__init__.py", line 138, in _install_setup_requires
         dist.fetch_build_eggs(dist.setup_requires)
       File "C:\Users\unk1nd\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\dist.py", line 695, in fetch_build_eggs
         resolved_dists = pkg_resources.working_set.resolve(
       File "C:\Users\unk1nd\AppData\Local\Programs\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 781, in resolve
         dist = best[req.key] = env.best_match(
       File "C:\Users\unk1nd\AppData\Local\Programs\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 1066, in best_match
         return self.obtain(req, installer)
       File "C:\Users\unk1nd\AppData\Local\Programs\Python\Python38\lib\site-packages\pkg_resources\__init__.py", line 1078, in obtain
         return installer(requirement)
       File "C:\Users\unk1nd\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\dist.py", line 754, in fetch_build_egg
         return fetch_build_egg(self, req)
       File "C:\Users\unk1nd\AppData\Local\Programs\Python\Python38\lib\site-packages\setuptools\installer.py", line 130, in fetch_build_egg
         raise DistutilsError(str(e))
     distutils.errors.DistutilsError: Command '['C:\\Users\\unk1nd\\AppData\\Local\\Programs\\Python\\Python38\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\unk1nd\\AppData\\Local\\Temp\\tmpgvlmkexz', '--quiet', '--find-links', 'https://github.com/kivy-garden/garden/archive/master.zip', 'cython!=0.27,!=0.27.2,<=0.29.10,>=0.24']' returned non-zero exit status 1.
    Using setuptools
    User distribution detected, avoid portable command.
    Using this graphics system: OpenGL
    WARNING: A problem occurred while running pkg-config --libs --cflags gstreamer-1.0 (code 1)

    b"'pkg-config' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n"

    WARNING: A problem occurred while running pkg-config --libs --cflags gstreamer-1.0 (code 1)

    b"'pkg-config' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n"
    WARNING: A problem occurred while running pkg-config --libs --cflags sdl2 SDL2_ttf SDL2_image SDL2_mixer (code 1)

    b"'pkg-config' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n"

    ERROR: Dependency for context.pyx not resolved: config.pxi
    ERROR: Dependency for compiler.pyx not resolved: config.pxi
    ERROR: Dependency for context_instructions.pyx not resolved: config.pxi
    ERROR: Dependency for fbo.pyx not resolved: config.pxi
    ERROR: Dependency for instructions.pyx not resolved: config.pxi
    ERROR: Dependency for opengl.pyx not resolved: config.pxi
    ERROR: Dependency for opengl_utils.pyx not resolved: config.pxi
    ERROR: Dependency for shader.pyx not resolved: config.pxi
    ERROR: Dependency for stencil_instructions.pyx not resolved: config.pxi
    ERROR: Dependency for scissor_instructions.pyx not resolved: config.pxi
    ERROR: Dependency for texture.pyx not resolved: config.pxi
    ERROR: Dependency for vbo.pyx not resolved: config.pxi
    ERROR: Dependency for vertex_instructions.pyx not resolved: config.pxi
    ERROR: Dependency for cgl.pyx not resolved: config.pxi
    ERROR: Dependency for cgl_mock.pyx not resolved: config.pxi
    ERROR: Dependency for cgl_gl.pyx not resolved: config.pxi
    ERROR: Dependency for cgl_glew.pyx not resolved: config.pxi
    ERROR: Dependency for cgl_sdl2.pyx not resolved: config.pxi
    ERROR: Dependency for svg.pyx not resolved: config.pxi
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by unk1nd** [comment]
needed to use python3.7.
Kivy did not support 3.8
