### ISSUE TITLE
mac os: "Bluetooth device is turned off" error

### ISSUE THREAD

**Issue by sehufnkjesktgna** [slinger360/NineRiFt-kivy#9]
On mac os 10.15, I get the following error when trying to connect via BLE:
`anaconda3/lib/python3.7/site-packages/bleak/backends/corebluetooth/discovery.py", line 35, in discover
     raise BleakError("Bluetooth device is turned off")
 bleak.exc.BleakError: Bluetooth device is turned off`

This is despite bluetooth being on.

**Comment by HelaFaye** [comment]
I'll look into it when I can. I don't own a Mac. Could you post a full log, please?

**Comment by billchurch** [comment]
Here's what I have for my setup.  macOS 10.14.6 and Python 3.7.7:
 
```
$ python3 ./main.py 
[INFO   ] [Logger      ] Record log in /Users/bill/.kivy/logs/kivy_20-05-03_2.txt
[INFO   ] [Kivy        ] v1.11.1
[INFO   ] [Kivy        ] Installed at "/usr/local/lib/python3.7/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.7.7 (default, Mar 10 2020, 15:43:03) 
[Clang 11.0.0 (clang-1100.0.33.17)]
[INFO   ] [Python      ] Interpreter at "/usr/local/opt/python/bin/python3.7"
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_imageio, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'2.1 ATI-2.11.21'>
[INFO   ] [GL          ] OpenGL vendor <b'ATI Technologies Inc.'>
[INFO   ] [GL          ] OpenGL renderer <b'AMD Radeon Pro 560 OpenGL Engine'>
[INFO   ] [GL          ] OpenGL parsed version: 2, 1
[INFO   ] [GL          ] Shading version <b'1.20'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [KivyMD      ] v0.104.1
[WARNING] [Factory     ] Ignored class "CommandScreen" re-declaration. Current -  module: None, cls: <class '__main__.CommandScreen'>, baseclass: None, filename: None. Ignored -  module: None, cls: None, baseclass: Screen, filename: /Users/bill/Documents/GitHub/NineRiFt-Lite/ninerift.kv.
[INFO   ] [tprint      ] Don't forget to post a review
selfile_filter set to ['*.bin.enc', '!.md5']
selfile_filter set to ['*.bin.enc', '!.md5']
selfile_filter set to ['*.bin.enc', '!.md5']
selfile_filter set to ['*.bin.enc', '!.md5']
[INFO   ] [Base        ] Start application main loop
[INFO   ] [GL          ] NPOT texture support is available
Starting event loop <_UnixSelectorEventLoop running=False closed=False debug=False>
[INFO   ] [tprint      ] BleakError('Bluetooth device is turned off')
Current state: connecting
Current state: disconnecting
Current state: disconnected
 Exception in thread Thread-5:
 Traceback (most recent call last):
   File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner
     self.run()
   File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 870, in run
     self._target(*self._args, **self._kwargs)
   File "/Users/bill/Documents/GitHub/NineRiFt-Lite/nbclient.py", line 125, in _connect_inner
     raise exc
   File "/Users/bill/Documents/GitHub/NineRiFt-Lite/nbclient.py", line 83, in _connect_inner
     ports = link.scan()
   File "/Users/bill/Documents/GitHub/NineRiFt-Lite/py9b/link/bleak.py", line 81, in scan
     ).result(timeout*3)
   File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 428, in result
     return self.__get_result()
   File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
     raise self._exception
   File "/usr/local/lib/python3.7/site-packages/bleak/backends/corebluetooth/discovery.py", line 31, in discover
     raise BleakError("Bluetooth device is turned off")
 bleak.exc.BleakError: Bluetooth device is turned off
```

**Comment by HelaFaye** [comment]
I will look into it but, that appears to be an issue with your system and not my software. I'll post any updates here but, I'm closing this issue for now.

**Comment by billchurch** [comment]
Hah. Ok 👌

**Comment by dhalbert** [comment]
@billchurch I'm getting the same issue in a completely different context (not with this repo's software). Did you figure this out? Thanks.
